import { Option } from "@/components/ui/multiple-selector";

export const REGION_OPTIONS: Option[] = [
  { value: "1", label: "Chișinău - Ciocana" },
  { value: "2", label: "Chișinău - Râșcani" },
  { value: "3", label: "Chișinău - Centru" },
  { value: "4", label: "Chișinău - Botanica" },
  { value: "5", label: "Chișinău - Buiucani" },
  { value: "6", label: "Bălți" },
  { value: "7", label: "Anenii Noi" },
  { value: "8", label: "Basarabeasca" },
  { value: "9", label: "Briceni" },
  { value: "10", label: "Cahul" },
  { value: "11", label: "Călărași" },
  { value: "12", label: "Cantemir" },
  { value: "13", label: "Căușeni" },
  { value: "14", label: "Ciadâr-Lunga" },
  { value: "15", label: "Cimișlia" },
  { value: "16", label: "Comrat" },
  { value: "17", label: "Criuleni" },
  { value: "18", label: "Dondușeni" },
  { value: "19", label: "Drochia" },
  { value: "20", label: "Edineț" },
  { value: "21", label: "Fălești" },
  { value: "22", label: "Florești" },
  { value: "23", label: "Glodeni" },
  { value: "24", label: "Hîncești" },
  { value: "25", label: "Ialoveni" },
  { value: "26", label: "Leova" },
  { value: "27", label: "Nisporeni" },
  { value: "28", label: "Ocnița" },
  { value: "29", label: "Orhei" },
  { value: "30", label: "Rezina" },
  { value: "31", label: "Rîșcani" },
  { value: "32", label: "Sîngerei" },
  { value: "33", label: "Soroca" },
  { value: "34", label: "Strășeni" },
  { value: "35", label: "Șoldănești" },
  { value: "36", label: "Ștefan-Vodă" },
  { value: "37", label: "Taraclia" },
  { value: "38", label: "Telenești" },
  { value: "39", label: "Ungheni" },
  { value: "40", label: "UTA Găgăuzia" }
];